/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aldinn
 */
public class apotekers extends javax.swing.JFrame { 
    
    private String[] namaObat;
    private String[] deskripsiObat;
    
    public apotekers() {
    initComponents();
    
    namaObat = new String[]{"Antangin", "Bodrex", "Orpen", "Heroxin", "Balsem",
                            "Noza", "Panadol", "TolakAngin", "Stimuno", "Viostin"};
    deskripsiObat = new String[]{ 
                "Mengatasi sakit pusing atau kepala beat.", 
                "Mengatasi gatal-gatal dan bintik-bintik merah.", 
                "Mengatasi gejala demam dan badan panas dingin.", 
                "Mengatasi gejala flu atau pilek.",
                "Mengatasi gejala sakit pinggang dan pegel linu.",
  
        };
    }

 private void tampilkanObat(String gejala, String[] namaObat, String[] deskripsiObat) {
        switch (gejala) {
            case "Pusing":
                NamaObat.setText("Nama Obat : " + namaObat[0] + " dan " + namaObat[1] + " dan " + namaObat[7]);
                Deskripsi.setText("Deskripsi     : " + deskripsiObat[0]);
                break;
            case "Gatal":
                NamaObat.setText("Nama Obat : " + namaObat[2] + " dan " + namaObat[3]);
                Deskripsi.setText("Deskripsi     : " + deskripsiObat[1]);
                break;
            case "Demam":
                NamaObat.setText("Nama Obat : " + namaObat[6] + " dan " + namaObat[8]);
                Deskripsi.setText("Deskripsi     : " + deskripsiObat[2]);
                break;
            case "Flu":
                NamaObat.setText("Nama Obat : " + namaObat[5]);
                Deskripsi.setText("Deskripsi     : " + deskripsiObat[3]);
                break;
            case "Nyeri Otot":
                NamaObat.setText("Nama Obat : " + namaObat[4] + " dan " + namaObat[9]);
                Deskripsi.setText("Deskripsi     : " + deskripsiObat[4]);
                break;
            default:
                NamaObat.setText("Nama Obat: ");
                Deskripsi.setText("Deskripsi     : ");
                break;
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        paneltombol = new javax.swing.JPanel();
        Pusing = new javax.swing.JButton();
        Gatal = new javax.swing.JButton();
        Demam = new javax.swing.JButton();
        Flu = new javax.swing.JButton();
        Nyeriotot = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        paneldeskripsi = new javax.swing.JPanel();
        LabelGaris2 = new javax.swing.JLabel();
        NamaObat = new javax.swing.JLabel();
        Deskripsi = new javax.swing.JLabel();
        LabelGaris3 = new javax.swing.JLabel();
        panelgambar = new javax.swing.JPanel();
        Antangin = new javax.swing.JLabel();
        Bodrex = new javax.swing.JLabel();
        Orpen = new javax.swing.JLabel();
        Heroxin = new javax.swing.JLabel();
        Balsem = new javax.swing.JLabel();
        Noza = new javax.swing.JLabel();
        Panadol = new javax.swing.JLabel();
        TolakAngin = new javax.swing.JLabel();
        Stimuno = new javax.swing.JLabel();
        Viostin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APOTEKERS");
        setMinimumSize(new java.awt.Dimension(700, 512));

        paneltombol.setBackground(new java.awt.Color(204, 204, 204));
        paneltombol.setMinimumSize(new java.awt.Dimension(750, 160));
        paneltombol.setPreferredSize(new java.awt.Dimension(750, 160));
        paneltombol.setLayout(new java.awt.GridBagLayout());

        Pusing.setBackground(new java.awt.Color(51, 255, 255));
        Pusing.setText("Pusing");
        Pusing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PusingActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 170, 23, 0);
        paneltombol.add(Pusing, gridBagConstraints);

        Gatal.setBackground(new java.awt.Color(51, 255, 255));
        Gatal.setText("Gatal");
        Gatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GatalActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 34, 23, 0);
        paneltombol.add(Gatal, gridBagConstraints);

        Demam.setBackground(new java.awt.Color(51, 255, 255));
        Demam.setText("Demam");
        Demam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemamActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 34, 23, 0);
        paneltombol.add(Demam, gridBagConstraints);

        Flu.setBackground(new java.awt.Color(51, 255, 255));
        Flu.setText("Flu");
        Flu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FluActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 34, 23, 0);
        paneltombol.add(Flu, gridBagConstraints);

        Nyeriotot.setBackground(new java.awt.Color(51, 255, 255));
        Nyeriotot.setText("Nyeri Otot");
        Nyeriotot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NyeriototActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 24, 23, 0);
        paneltombol.add(Nyeriotot, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Pilih Gejala");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.insets = new java.awt.Insets(0, 34, 0, 0);
        paneltombol.add(jLabel3, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(256, 92));
        jPanel2.setPreferredSize(new java.awt.Dimension(256, 85));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Toshiba\\Downloads\\A__1_-removebg-preview.png")); // NOI18N
        jPanel2.add(jLabel2);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("APOTEKERS");
        jPanel2.add(jLabel1);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Toshiba\\Downloads\\A__1_-removebg-preview.png")); // NOI18N
        jPanel2.add(jLabel4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = 614;
        gridBagConstraints.ipady = -12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        paneltombol.add(jPanel2, gridBagConstraints);

        getContentPane().add(paneltombol, java.awt.BorderLayout.PAGE_START);

        paneldeskripsi.setBackground(new java.awt.Color(51, 255, 255));
        paneldeskripsi.setPreferredSize(new java.awt.Dimension(859, 60));
        paneldeskripsi.setLayout(new javax.swing.BoxLayout(paneldeskripsi, javax.swing.BoxLayout.PAGE_AXIS));

        LabelGaris2.setText("----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        paneldeskripsi.add(LabelGaris2);

        NamaObat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NamaObat.setText("Nama Obat :");
        paneldeskripsi.add(NamaObat);

        Deskripsi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Deskripsi.setText("Deskripsi     :");
        paneldeskripsi.add(Deskripsi);

        LabelGaris3.setText("----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        paneldeskripsi.add(LabelGaris3);

        getContentPane().add(paneldeskripsi, java.awt.BorderLayout.PAGE_END);

        panelgambar.setBackground(new java.awt.Color(204, 255, 255));
        panelgambar.setLayout(new java.awt.GridLayout(2, 5));

        Antangin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ANTANGIN1.png"))); // NOI18N
        Antangin.setText("Antangin");
        panelgambar.add(Antangin);

        Bodrex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BODREX1.png"))); // NOI18N
        Bodrex.setText("Bodrex");
        panelgambar.add(Bodrex);

        Orpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ORPEN1.png"))); // NOI18N
        Orpen.setText("Orpen");
        panelgambar.add(Orpen);

        Heroxin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HEROCYN1.png"))); // NOI18N
        Heroxin.setText("Heroxin");
        panelgambar.add(Heroxin);

        Balsem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BALSEM1.png"))); // NOI18N
        Balsem.setText("Balsem");
        panelgambar.add(Balsem);

        Noza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NOZA1.png"))); // NOI18N
        Noza.setText("Noza");
        panelgambar.add(Noza);

        Panadol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PANADOL1.png"))); // NOI18N
        Panadol.setText("Panadol");
        panelgambar.add(Panadol);

        TolakAngin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TOLAK_ANGIN1.png"))); // NOI18N
        TolakAngin.setText("Tolak Angin");
        panelgambar.add(TolakAngin);

        Stimuno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/STIMUNO1.png"))); // NOI18N
        Stimuno.setText("Stimuno");
        panelgambar.add(Stimuno);

        Viostin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISOTIN1.png"))); // NOI18N
        Viostin.setText("Viostin");
        panelgambar.add(Viostin);

        getContentPane().add(panelgambar, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PusingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PusingActionPerformed
        // TODO add your handling code here:
        tampilkanObat("Pusing", namaObat, deskripsiObat);
    }//GEN-LAST:event_PusingActionPerformed

    private void FluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FluActionPerformed
        // TODO add your handling code here:
        tampilkanObat("Flu", namaObat, deskripsiObat);
    }//GEN-LAST:event_FluActionPerformed

    private void NyeriototActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NyeriototActionPerformed
        // TODO add your handling code here:
        tampilkanObat("Nyeri Otot", namaObat, deskripsiObat);
    }//GEN-LAST:event_NyeriototActionPerformed

    private void DemamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemamActionPerformed
        // TODO add your handling code here:
        tampilkanObat("Demam", namaObat, deskripsiObat);
    }//GEN-LAST:event_DemamActionPerformed

    private void GatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GatalActionPerformed
        // TODO add your handling code here:
        tampilkanObat("Gatal", namaObat, deskripsiObat);
    }//GEN-LAST:event_GatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(apotekers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(apotekers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(apotekers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(apotekers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new apotekers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Antangin;
    private javax.swing.JLabel Balsem;
    private javax.swing.JLabel Bodrex;
    private javax.swing.JButton Demam;
    private javax.swing.JLabel Deskripsi;
    private javax.swing.JButton Flu;
    private javax.swing.JButton Gatal;
    private javax.swing.JLabel Heroxin;
    private javax.swing.JLabel LabelGaris2;
    private javax.swing.JLabel LabelGaris3;
    private javax.swing.JLabel NamaObat;
    private javax.swing.JLabel Noza;
    private javax.swing.JButton Nyeriotot;
    private javax.swing.JLabel Orpen;
    private javax.swing.JLabel Panadol;
    private javax.swing.JButton Pusing;
    private javax.swing.JLabel Stimuno;
    private javax.swing.JLabel TolakAngin;
    private javax.swing.JLabel Viostin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel paneldeskripsi;
    private javax.swing.JPanel panelgambar;
    private javax.swing.JPanel paneltombol;
    // End of variables declaration//GEN-END:variables

}
